---

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: Update dnf/yum cache
  ansible.builtin.yum:
    update_cache: true
  when: ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum'

- name: Install packages
  ansible.builtin.package:
    name: keepalived

- name: Create directory for keepalived
  file:
    path: /etc/keepalived
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Kubernetes API health check script
  template:
    src: templates/check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh
    owner: root
    group: root
    mode: 0755
  notify: restart keepalived

- name: Create keepalived config file
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  notify: restart keepalived

- name: Enable keepalived and make sure it is not masked
  systemd:
    name: keepalived
    enabled: yes
    masked: no
  notify: restart keepalived

- name: Flush handlers
  meta: flush_handlers
