---

- name: Install Keepalived when HA mode is enabled
  ansible.builtin.include_tasks: keepalived.yml
  when:
    - rke2_api_ip is defined
    - inventory_hostname in groups[rke2_servers_group_name]
    - rke2_ha_mode | bool
    - rke2_ha_mode_keepalived | bool

- name: Download and install RKE2 {{ rke2_version }}
  ansible.builtin.include_tasks: rke2.yml

- name: CIS Hardening
  ansible.builtin.include_tasks: cis.yml
  when:
    - rke2_cis_profile | length > 0

- name: Find Active Server
  ansible.builtin.include_tasks: find_active_server.yml
  when:
    - rke2_ha_mode | bool

- name: Enable IPVS kernel module
  community.general.modprobe:
    name: ip_vs
    state: present
    persistent: present
  when:
    - rke2_kubevip_ipvs_lb_enable | bool
    - inventory_hostname in groups[rke2_servers_group_name]
    - rke2_ha_mode | bool
    - rke2_ha_mode_kubevip | bool
    - not rke2_ha_mode_keepalived | bool


- name: Copy kube-vip manifests to the masternode
  ansible.builtin.include_tasks: kubevip.yml
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0
    - rke2_ha_mode | bool
    - rke2_ha_mode_kubevip | bool
    - not rke2_ha_mode_keepalived | bool

- name: Copy ingress-nginx manifests to the masternode
  ansible.builtin.include_tasks: ingress-nginx.yml
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0

- name: Prepare very first server node in the cluster
  ansible.builtin.include_tasks: first_server.yml
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0
    - active_server is not defined

- name: Restore etcd specific tasks
  ansible.builtin.include_tasks: first_server_restore.yml
  when:
    - inventory_hostname == active_server or inventory_hostname == groups[rke2_servers_group_name].0
    - do_etcd_restore is defined or do_etcd_restore_from_s3 is defined

- name: Prepare and join remaining nodes of the cluster
  ansible.builtin.include_tasks: remaining_nodes.yml
  when:
    - active_server is defined
    - groups[rke2_cluster_group_name] | length | int >= 2

- name: "{{ _loop_name }}"
  ansible.builtin.include_tasks: rolling_loop.yml
  vars:
    _loop_name: Rolling cordon and drain restart when version changes
    _loop_over_tasks: rolling_restart.yml
  when:
    - rke2_restart_allowed
    - rke2_restart_needed
    - installed_version != "not installed"
    - rke2_version != running_version

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: "{{ _loop_name }}"
  ansible.builtin.include_tasks: rolling_loop.yml
  vars:
    _loop_name: Rolling restart when config files change
    _loop_over_tasks: rolling_restart.yml
    # drain not required for config change only
    rke2_drain_node_during_upgrade: false
  when:
    - rke2_restart_allowed
    - rke2_restart_needed

- name: Final steps
  ansible.builtin.include_tasks: summary.yml
