---

- name: Install Keepalived when HA mode is enabled
  include_tasks: keepalived.yml
  when:
    - rke2_api_ip is defined
    - inventory_hostname in groups.masters
    - rke2_ha_mode

- name: Download and install RKE2
  include_tasks: rke2.yml

- name: Find Active Server
  include_tasks: find_active_server.yml
  when:
    - rke2_ha_mode | bool

- name: Prepare very first server node in the cluster
  include_tasks: first_server.yml
  when:
    - inventory_hostname == groups.masters.0
    - active_server is not defined

- name: Prepare and join remaining nodes of the cluster
  include_tasks: ramaining_nodes.yml
  when:
    - active_server is defined
    - groups.k8s_cluster | length | int >= 2

- name: Final steps
  include_tasks: summary.yml
