---

- name: Install Keepalived when HA mode is enabled
  ansible.builtin.include_tasks: keepalived.yml
  when:
    - rke2_api_ip is defined
    - inventory_hostname in groups[rke2_servers_group_name]
    - rke2_ha_mode | bool
    - rke2_ha_mode_keepalived | bool

- name: Download and install RKE2 {{ rke2_version }}
  ansible.builtin.include_tasks: rke2.yml

- name: Find Active Server
  ansible.builtin.include_tasks: find_active_server.yml
  when:
    - rke2_ha_mode | bool

- name: Prepare very first server node in the cluster
  ansible.builtin.include_tasks: first_server.yml
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0
    - active_server is not defined

- name: copy kube-vip manifests to the masternode
  ansible.builtin.include_tasks: kubevip.yml
  when:
    - inventory_hostname == groups[rke2_servers_group_name].0
    - rke2_ha_mode | bool
    - rke2_ha_mode_kubevip | bool
    - not rke2_ha_mode_keepalived | bool

- name: Prepare and join remaining nodes of the cluster
  ansible.builtin.include_tasks: remaining_nodes.yml
  when:
    - active_server is defined
    - groups[rke2_cluster_group_name] | length | int >= 2

- name: Rolling restart
  ansible.builtin.include_tasks: rolling_restart.yml
  with_items: "{{ groups[rke2_cluster_group_name] }}"
  loop_control:
    loop_var: _host_item
  when: ( hostvars[_host_item].inventory_hostname == inventory_hostname ) and installed_rke2_version.stdout is defined and rke2_version != ( installed_rke2_version.stdout | default({}) )

- name: Final steps
  ansible.builtin.include_tasks: summary.yml
